# Generated by Django 3.0.8 on 2020-08-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
